[build]
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Configuración para que todas las rutas apunten al index.html para SPA
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = [""]}