backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "productos"
    label: "Productos"
    folder: "productos"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "nombre", label: "Nombre" }
      - { name: "descripcion", label: "Descripción", widget: "text" }
      - { name: "precio", label: "Precio" }
      - { name: "imagen", label: "Imagen", widget: "image" }
